language: go

os:
  - linux
  - osx

git:
  submodules: false

addons:
  apt:
    packages:
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libgit2-dev

script:
  - make test
